### ISSUE TITLE
placing order through woocommerce bKash not working 

### ISSUE THREAD

**Issue by TahsinAbrar** [tareq1988/woocommerce-bkash#1]
I've got this error when I place an order through bKash with ["woocommerce-bKash"](https://wordpress.org/plugins/woocommerce-bkash/) plugin. 

> Warning: file_get_contents(http://www.bkashcluster.com:9080/dreamwave/merchant/trxcheck/sendmsg?user=XXXXXXX&pass=XXXXXXX&msisdn=&trxid=XXXXXXX): failed to open stream: Connection refused in /home/XXXXXXX/public_html/wp-content/plugins/woocommerce-bkash/gateway.php on line 109
> 
> Fatal error: Call to undefined method WooCommerce::add_error() in /home/XXXXXXX/public_html/wp-content/plugins/woocommerce-bkash/gateway.php on line 135

Did you also get this error? Or do I need to configure something else to solve this error?

Thanks.

**Comment by tareq1988** [comment]
The warning: So far, it seems like your server issue. Going to that URL doesn't throw you any exception.

About the fatal error: I developed the plugin a long time ago, in the meantime WooCommerce has changed a lot, so I guess I have to change some things.

Thanks for reporting :)

**Comment by tareq1988** [comment]
Fixed in v1.0
