### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by bappi** [tareq1988/woocommerce-bkash#3]
Just a little heads up. In your readme.txt it says 

"Here is how to use:

Download the plugin from WordPress.org. Typically, # you're developer will do it for you, if you're not a developer yourself."

Where it should be "your" I think.

Install and active it, as # you're normally install and active other plugin # too
Should be Install and active it, as you normally install and active other plugins

Give it a revision overall if possible, thanks

**Comment by tareq1988** [comment]
Thanks for catching the typo mistake 👍
